name: Build

on:
  push:
    branches: ["**"]
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
 
    - name: BuildTools cache
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository/org/spigotmc/spigot
        key: ${{ runner.os }}-maven-${{ hashFiles('./.github/workflows/buildtools.sh') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: BuildTools
      run: |
        sh ./.github/workflows/buildtools.sh
 
    - name: Build
      run: |
        mvn clean install -pl :timer-plugin-bukkit,:timer-plugin-bungee -B -am "-Drevision=$(git describe --tags `git rev-list --tags --max-count=1`)"
        mkdir dist
        mv timer-plugin/*/target/timer-*.jar ./dist
        mv timer-api/timer-api-core/target/timer-*.jar ./dist
        mv timer-core/target/timer-*.jar ./dist

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Plugin
        path: dist/